### ISSUE TITLE
Install script for installing the agent-in-k8s container onto the edge cluster

### ISSUE THREAD

**Issue by MaxMcAdam** [open-horizon/anax#1569]
Install the agent-in-k8s container onto the edge cluster.  The script should be usable when installing the agent into a pre-existing edge cluster. It might be the same script used to install the agent onto a device.
The deployment will need a persistent volume (so that the agent container could be dynamically moved to another worker node), and a service account.Replica count will ALWAYS be 1. Anything else is not supported.
The OS inside the agent container will be ubuntu.

- [x] Manually deploy agent container with existing ubuntu based image to k8s, and hzn register inside container. (deployment, pod, persistent volume, configmap, secret, etc...) 
- [x] Create a alpine based anax image and a ubi for k8s deployment. Add targets in the Makefile to create the k8s anax image and push the image.
- [x] Deploy the anax k8s images (alpine based and ubi) to k8s cluster. (Need to revisit k8s files)
- [x] Deploy anax in e2edev environment
- [ ] ~~Create agent install script for k8s, to automate the agent install process~~ (move to a new issue #1627)
