### ISSUE TITLE
Add single node K8s to e2edev

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1577]
- [x] Try to get Microk8s running
- [ ] Include Microk8s in e2edev startup and shutdown
- [ ] Deploy agent into microk8s
- [ ] Update ./test/README.md
