### ISSUE TITLE
Add nodeType on node and new service attributes for services

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1581]
- [x] `hzn node list`, and `hzn exchange node list` show the node type
- [x] add a -T flag for `hzn node create` and `hzn register` for node type
- [x] add clusterDeployment, clusterDeploymentSignature to service resource
- [x] `hzn exchange service list` shows the new service attributes
- [x]  anax/exchange and anax/persistence changes for node type and service attributes
