### ISSUE TITLE
hzn commands handle new node  and service attributes

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1582]
- [x] `hzn exchange service publish` 
     1. validates the service type and verifies consistence for the dependent service types
     2. Userinput is not supported for cluster services, and requiredServices are also not supported.
     3. zip up the operator metadata and add it to the service definition. (The new cluster deployment config contains all of the files from the ./deploy directory in the operator project. The metadata files will be zipped up and then the binary zip file is converted to a base64 encoded string which is stored in the cluster deployment config section in a deployed service definition in the exchange. The cluster deployment config is signed as usual. This way the zipped metadata file is captured by value and never needs to be uploaded anywhere.) 
- [x] `hzn exchange service verify`
    Verifies the signature for both deployment and cluster deployment.
- [x] `hzn exchange node create`
    1.  validate the node type.
