### ISSUE TITLE
Add a new set of plugins in agent to handle k8s cluster deployment

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1589]
- [x] The cluster deployment config in a service definition is pluggable just like the device deployment config, so we need to add a new set of plugins. The new one for this release (in a package called kube_operator, with a new anax worker to support it) will work similar to how the Helm deployment config works. The code can be modeled on the Helm deployment config and the Helm worker.
- [x] The Helm deployment config plugin and worker should be disabled in this release. 
- [x] The container worker and Image Fetch workers might be able to terminate themselves when running on an edge cluster agent. 
- [x] Fix agent so that MultipleAnaxInstances can be set to false in the agent k8s container config file.
- [x] Fix agent to ensure that it never creates a go-docker client when running in k8s, then remove "DockerEndpoint" from the agent k8s container config file.
