### ISSUE TITLE
Deploy service in k8s clusters for an agreement

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1591]
Deploy service in k8s clusters for an agreement
- [x] install the operator, deploy it's app when an agreement is formed. 
    - [x] reconstitute the yaml metadata
    - [x] convert the yaml to k8s client-go api objects
    - [x] create the specified resources in the cluster
- [x] add hzn env vars to config map
When a service is deployed by an edge cluster agent, the agent will reconstitute the yaml metadata (from the service definition) needed to install the operator. No HZN env vars will be passed in, including no userinput.
The deployment of the operator is modified by the agent before starting it to add an env var (HZN_ENV_VARS) for the config map which contains the HZN env vars.
Then the agent will use the "k8s.io/client-go" package to install the operator and tell it to deploy an instance of the app.
- [x]  Remove operator when the agreement is cancelled.
Depends on #1589, #1590
