### ISSUE TITLE
Additions to agent-install.sh for SDO

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1614]
When an SDO device boots and gets connected to the proper IEAM instance, `agent-install.sh` will be run on it to install the anax agent and register it for policy. Most of the functionality is already present in `agent-install.sh`, but a few additions are needed for what is unique about this scenario:

- [ ] The node resource (and node policy resource) will be pre-created in the exchange. So `agent-install.sh` needs to be able to accept the node creds instead of the user creds. For completeness, it should accept the node creds in any of the 3 ways it currently accepts users creds, i.e.: via a cmd line flag, in `HZN_EXCHANGE_NODE_AUTH` env var,  or in `HZN_EXCHANGE_NODE_AUTH` in the config file. Further, it should use the same logic as `hzn register`: 
  - If only node creds are specified, and the node exists in the exchange, use that (if the user creds are specified they are ignored)
  - If node and user creds are specified, and the node does not already exist, create the node with that id and token
  - If the node doesn't exist and user creds are specified, same behavior as today
  - If the node doesn't exist and user creds aren't specified, same behavior as today

**Comment by t-fine** [comment]
- [ ] Accept the node creds in any of the 3 ways it currently accepts users creds, i.e.: via a cmd line flag, in `HZN_EXCHANGE_NODE_AUTH` env var,  or in `HZN_EXCHANGE_NODE_AUTH` in the config file
  - [ ]  If only node creds are specified, and the node exists in the exchange, use that (if the user creds are specified they are ignored)
  - [ ] If node and user creds are specified, and the node does not already exist, create the node with that id and token
  - [ ] If the node doesn't exist and user creds are specified, same behavior as today
  - [ ] If the node doesn't exist and user creds aren't specified, same behavior as today
