### ISSUE TITLE
'hzn voucher import' sub-command for SDO

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#1615]
`hzn voucher import -f <voucher-file> [-e|--example <example-name>] [--policy <node-policy-file>]`

- [x] Refine current scripts' error checking, configurability, rerunnability, documentation
- [x] Import voucher by running the ocs-api: POST /voucher
- [x] Create the node resource with: `id=<device UUID>, token=<randomly generated>`
- [x] If `-e` or `--policy specified`, creates a node policy resource:
  - [x] For `-e`: `{ "properties": [ { "name": "openhorizon.example", "value": "helloworld" } ] }`
  - [x] For `--policy specified`: use file name to create node policy
- [x] Add support for voucher tar file to import many vouchers at once
- [x] Also implement `hzn voucher inspect`
- [x] Configure `owner-companion-service` DB (files) to download creds, config, cert, and script to device:
  - [x] Node id/token to device
  - [x] Cfg file: `HZN_EXCHANGE_URL`, `HZN_FSS_CSSURL`, `HZN_ORG_ID`
  - [x] The management hub self-signed certificate
  - [x] `agent-install.sh`
