### ISSUE TITLE
Remove the image field from clusterDeployment object

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1660]
- [x] remove the image field from clusterDeployment object from deployment process (Max)
- [x] remove the image field from clusterDeployment object from service (Ling)
- [x] remove the image field from clusterDeployment object from persistence (Ling)

**Comment by linggao** [comment]
Removed operator_image field, changes yaml_archive to operatorYamlArchive.
