### ISSUE TITLE
Eliminate continual policy scans  in the agbot when nothing is changing

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1698]
- [x] Only perform searches when something (pattern, policy, node, node agreement) has changed.
- [x] Provide a configurable interval (FullScanS) in which a full scan of all internal policies is performed even though nothing has changed in that time period. This is a catch-all in case a change was missed.
- [x] Retry specific agreement making requests if they fail instead of re-scanning all policies.
- [x] Fix consumer protocol handler thread safety. The map of CPHs needs to be protected by a lock since it is accessed on multiple threads.
- [x] Lock buffered work queues in prioritized work queue so that buffer queue size can be monitored.
- [x] Handle errors on the exchange .../search APIs
- [x] Increase the default protocol timeout to account for agents that reach the default 2 min heartbeat interval.
