### ISSUE TITLE
Feature Request: Agent RHEL 8.6 support

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/anax#3228]
### Open Horizon support for the RHEL 8.6 Linux distribution

This will be the master ticket to drive support for Open Horizon on the RHEL 8.6 linux distribution
Several tickets will be linked to this ticket:

- [x] - Add RHEL 8.6 to Makefile (details???)
- [x] - Add RHEL 8.6 to agent_install.sh - https://github.com/open-horizon/anax/issues/3229
- [x] - Add RHEL 8.6 agent binaries to [edgeNodeFIles.sh](https://github.com/open-horizon/anax/blob/master/agent-install/edgeNodeFiles.sh) so they publish to CSS
- [x] - Ensure Dockerfile builds container that works on RHEL 8.6 in both Docker and podman 
- [ ] - Get RHEL 8.6 files added to Jenkins build pipeline (or whatever replaces it) so it arrives in [GitHub Releases](https://github.com/open-horizon/anax/releases)
- [ ] - Test / Validate and modify existing tests for the x86_64 anax binary on RHEL 8.6
- [ ] - Validate Examples on RHEL 8.6 - https://github.com/open-horizon/examples/issues/534
- [x] - Documentation updates to support RHEL 8.6 - https://github.com/open-horizon/open-horizon.github.io/issues/260

**Comment by johnwalicki** [comment]
I've been mostly thinking about x86_64 agent support.

We should also discuss if Open Horizon will support RHEL 8.6 as a supported edge device on **ppc64le**.

**Comment by johnwalicki** [comment]
PR #3231 has been staged for #3229

**Comment by johnwalicki** [comment]
@joewxboy  I inspected `edgeNodeFiles.sh` and no changes are required there to support RHEL 8.6 RPMs.

**Comment by johnwalicki** [comment]
@joewxboy  I inspected all of the Makefiles and no changes are required to support RHEL 8.6

```sh
$ find . -name Makefile
./test/docker/fs/hzn/service/hello/Makefile
./test/docker/fs/hzn/service/usehello/Makefile
./test/docker/fs/hzn/service/cpu/Makefile
./test/docker/fs/hzn/service/leaf/Makefile
./test/docker/fs/helm/hello/Makefile
./test/docker/fs/helm/hello/external/Makefile
./test/Makefile
./Makefile
./pkg/deb/Makefile
./pkg/mac/Makefile
./pkg/rpm/horizon-cli/Makefile
./pkg/rpm/horizon/Makefile
./pkg/rpm/Makefile
```

**Comment by johnwalicki** [comment]
@joewxboy I inspected all of the `Dockerfiles` and no changes are required to support RHEL 8.6

```sh
$ find . -name Dockerfile 
./test/docker/fs/hzn/service/hello/Dockerfile
./test/docker/fs/hzn/service/usehello/Dockerfile
./test/docker/fs/hzn/service/cpu/Dockerfile
./test/docker/fs/hzn/service/leaf/Dockerfile
./test/docker/fs/helm/hello/Dockerfile
./test/docker/Dockerfile
./ess/image/edge-sync-service-armhf/Dockerfile
./ess/image/edge-sync-service-arm64/Dockerfile
./css/image/cloud-sync-service-armhf/Dockerfile
./css/image/cloud-sync-service-arm64/Dockerfile
```

**Comment by johnwalicki** [comment]
@linggao has graciously merged #3231  - which adds support for RHEL 8.6.  Once devops does a build, we can test.

**Comment by joewxboy** [comment]
@johnwalicki Is it possible to make an issue template based on the description in this issue for future usage?

**Comment by johnwalicki** [comment]
@joewxboy  Good idea. #3232 
Will create an issue template in the anax repo.

**Comment by johnwalicki** [comment]
@joewxboy PR submitted to the anax repo which adds Issue templates for new Linux distro releases and microprocessor architectures.  See https://github.com/open-horizon/anax/pull/3233

**Comment by johnwalicki** [comment]
My RHEL 8.6 testing discovered that `lsb_release -si` reports `RedHatEnterprise` as the Linux distro variant.  A new issue #3246   and PR  #3247 fixed that.

These enhancements have been incorporated into the anax https://github.com/open-horizon/anax/releases/tag/v2.30.0-890  release.

Closing ticket as complete.
